modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="messingaround"
version="${mod_version}"
displayName="Messing Around"
authors="Berserk007"
description="Just messing around"


[[dependencies.messingaround]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.messingaround]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1, 1.22)"
    ordering="NONE"
    side="BOTH"
